
-- 암호화 테스트
SELECT password('abcd') AS pwd, MD5('abcd') AS md5
 , HEX(AES_ENCRYPT('abcd', 'ds')) AS ec
 , UNHEX('EF57C8500355411F7CFEE518FB6BCAF4') AS uh 
 , AES_DECRYPT(UNHEX('EF57C8500355411F7CFEE518FB6BCAF4'), 'ds') AS dc

-- View Log
CREATE TABLE IF NOT EXISTS `LOG_CONTENTS_VIEW` (
  `MENU_SEQ`	int(11) NOT NULL,
  `CONT_SEQ`	int(11) NOT NULL,
  `USER_ID`	varchar(20) NOT NULL,
  `VIEW_DT`	datetime NOT NULL,
  KEY `IX_CONTENTS_VIEW_SEQ` (`MENU_SEQ`, `CONT_SEQ`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Code
CREATE TABLE IF NOT EXISTS `TBL_COMMON_CODE` (
  `CODE_SEQ`	int(11) NOT NULL AUTO_INCREMENT,
  `CODE_GROUP`	varchar(20) NOT NULL,
  `CODE_ID`	varchar(20) NOT NULL,
  `CODE_NAME`	varchar(50) NOT NULL,
  `CODE_VALUE`	varchar(50) NOT NULL,
  `CREATE_DT`	datetime DEFAULT NULL,
  `CREATE_ID`	varchar(20) DEFAULT NULL,
  `UPDATE_DT`	datetime DEFAULT NULL,
  `UPDATE_ID`	varchar(20) DEFAULT NULL,
  PRIMARY KEY (`CODE_SEQ`),
  UNIQUE KEY `IX_COMMON_CD_GROUP` (`CODE_GROUP`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Site Menu 
CREATE TABLE IF NOT EXISTS `TBL_SITE_MENU` (
  `MENU_SEQ`	int(11) NOT NULL AUTO_INCREMENT,
  `MENU_AT_YN`	char(1) NOT NULL,
  `MENU_GP_CD`	varchar(20) NOT NULL,
  `MENU_TP_CD`	varchar(20) NOT NULL,
  `MENU_NAME`	varchar(50) NOT NULL,
  `MENU_VIEW`	varchar(100) NOT NULL,
  `MENU_PATH`	varchar(200) NOT NULL,
  `CREATE_DT`	datetime DEFAULT NULL,
  `CREATE_ID`	varchar(20) DEFAULT NULL,
  `UPDATE_DT`	datetime DEFAULT NULL,
  `UPDATE_ID`	varchar(20) DEFAULT NULL,
  PRIMARY KEY (`MENU_SEQ`),
  KEY `IX_SITE_MENU_GROUP` (`MENU_GP_CD`),
  KEY `IX_SITE_MENU_TYPE` (`MENU_TP_CD`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Member 
CREATE TABLE IF NOT EXISTS `TBL_MEMBER` (
  `USER_SEQ`	int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID`	varchar(20) NOT NULL,
  `USER_PW`	varchar(255) NOT NULL,
  `USER_NM`	varchar(50) NOT NULL,
  `USER_LV_CD`	varchar(20) NOT NULL,
  `USER_TP_CD`	varchar(20) NOT NULL,			
  `USER_Email`	varchar(255) DEFAULT NULL,
  `USER_Tel`	varchar(255) DEFAULT NULL,
  `USER_Mobile`	varchar(255) DEFAULT NULL,
  `CREATE_DT`	datetime DEFAULT NULL,
  `CREATE_ID`	varchar(20) DEFAULT NULL,
  `UPDATE_DT`	datetime DEFAULT NULL,
  `UPDATE_ID`	varchar(20) DEFAULT NULL,
  `LOGIN_CNT`	int(11) DEFAULT NULL,
  `LOGIN_DT`	datetime DEFAULT NULL,
  `LOGIN_IP`	varchar(20) DEFAULT NULL,
  PRIMARY KEY (`USER_SEQ`),
  UNIQUE KEY `IX_MEMBER_UID` (`USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Member Auth.
CREATE TABLE IF NOT EXISTS `TBL_MEMBER_AUTH` (
  `AUTH_SEQ`	int(11) NOT NULL AUTO_INCREMENT,  
  `MENU_SEQ`	int(11) NOT NULL,
  `AUTH_TP_CD`	varchar(20) NOT NULL,		-- Group 인증, User 인증?   
  `USER_LV_CD`	varchar(20) NOT NULL,
  `USER_ID`	varchar(20) NOT NULL,  
  `AUTH_LIST_YN`	char(1) NOT NULL,
  `AUTH_VIEW_YN`	char(1) NOT NULL,  
  `AUTH_INSERT_YN`	char(1) NOT NULL,
  `AUTH_MODIFY_YN`	char(1) NOT NULL,
  `AUTH_DELETE_YN`	char(1) NOT NULL,
  `AUTH_EXPORT_YN`	char(1) NOT NULL,
  `CREATE_DT`	datetime DEFAULT NULL,
  `CREATE_ID`	varchar(20) DEFAULT NULL,
  `UPDATE_DT`	datetime DEFAULT NULL,
  `UPDATE_ID`	varchar(20) DEFAULT NULL,
  PRIMARY KEY (`AUTH_SEQ`),
  KEY `IX_MENU_AUTH_GROUP` (`MENU_SEQ`, `AUTH_TP_CD`, `USER_LV_CD`),  
  KEY `IX_MENU_AUTH_USER` (`MENU_SEQ`, `AUTH_TP_CD`, `USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;






-- Customer
CREATE TABLE IF NOT EXISTS `TBL_CUSTOMER` (
  `CUS_SEQ`	int(11) NOT NULL AUTO_INCREMENT,
  `CUS_TP_CD`	varchar(20) NOT NULL,
  `CUS_NM`	varchar(50) NOT NULL,
  `CUS_Email`	varchar(255) DEFAULT NULL,
  `CUS_Tel`	varchar(255) DEFAULT NULL,
  `CUS_Mobile`	varchar(255) DEFAULT NULL,
  `CUS_ZIP_CD`	varchar(10) DEFAULT NULL,
  `CUS_ADDR1`	varchar(200) DEFAULT NULL,
  `CUS_ADDR2`	varchar(200) DEFAULT NULL,
  `CREATE_DT`	datetime DEFAULT NULL,
  `CREATE_ID`	varchar(20) DEFAULT NULL,
  `UPDATE_DT`	datetime DEFAULT NULL,
  `UPDATE_ID`	varchar(20) DEFAULT NULL,
  PRIMARY KEY (`CUS_SEQ`),
  KEY `IX_CUSTOMER_TP` (`CUS_TP_CD`),
  KEY `IX_CUSTOMER_NM` (`CUS_NM`),
  KEY `IX_CUSTOMER_TEL` (`CUS_Tel`),
  KEY `IX_CUSTOMER_MOBILE` (`CUS_Mobile`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
